// Generated by ts-to-zod
import { z } from "zod";

const axesConfigSchema = z.object({
  axes: z.array(z.any()),
  showAxesTooltip: z.boolean(),
});

const paletteConfigSchema = z.object({
  colorPaletteSize: z.number(),
  colorPalette: z.string(),
  usePalette: z.boolean(),
  colorPaletteReverse: z.boolean(),
});

const radialConfigSchema = z.object({
  innerRadius: z.number(),
  outerRadius: z.number(),
});

const valueConfigSchema = z.object({
  min: z.any(),
  max: z.any(),
  logScale: z.boolean(),
  logScaleBase: z.number(),
});
